export default [
  [
    "The wolf huffed and he puffed. He",
    "puffed and he huffed; but he could not",
    "blow the house down. At last, he was",
    "so out of breath that he couldn't huff",
    "and he couldn't puff anymore. So he",
    "stopped to rest and thought a bit.",
    "",
    "But this was too much. The wolf",
    "danced about with rage and swore he",
    "would come down the chimney and",
    "eat up the little pig for his supper.",
    "",
    "But while he was climbing on to the",
  ],
  [
    "roof the little pig prepared a big pot full of",
    "water to boil and made up a blazing",
    "fire.🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥",
    "",
    "Then, just as the wolf was coming down the",
    "chimney, the little piggy pulled off the lid,",
    "and plop! in fell the wolf into the scalding",
    "water.",
    "",
    "So the little piggy put on the cover again,",
    "and boiled the wolf up, and the three little",
    "pigs ate him for supper.",
  ],
];
